// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SendSms service

func NewSendSmsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SendSms service

type SendSmsService interface {
	SendSms(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type sendSmsService struct {
	c    client.Client
	name string
}

func NewSendSmsService(name string, c client.Client) SendSmsService {
	return &sendSmsService{
		c:    c,
		name: name,
	}
}

func (c *sendSmsService) SendSms(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SendSms.SendSms", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SendSms service

type SendSmsHandler interface {
	SendSms(context.Context, *Request, *Response) error
}

func RegisterSendSmsHandler(s server.Server, hdlr SendSmsHandler, opts ...server.HandlerOption) error {
	type sendSms interface {
		SendSms(ctx context.Context, in *Request, out *Response) error
	}
	type SendSms struct {
		sendSms
	}
	h := &sendSmsHandler{hdlr}
	return s.Handle(s.NewHandler(&SendSms{h}, opts...))
}

type sendSmsHandler struct {
	SendSmsHandler
}

func (h *sendSmsHandler) SendSms(ctx context.Context, in *Request, out *Response) error {
	return h.SendSmsHandler.SendSms(ctx, in, out)
}
